KK419817 implement Deploy step in jenkinsfile

diff --git a/ITE/GCL3/KK419817/Sprawozdanie2/Jenkinsfile b/ITE/GCL3/KK419817/Sprawozdanie2/Jenkinsfile
--- a/ITE/GCL3/KK419817/Sprawozdanie2/Jenkinsfile
+++ b/ITE/GCL3/KK419817/Sprawozdanie2/Jenkinsfile
@@ -8,6 +8,11 @@ pipeline {
     }
 
     stages {
+         stage('Pre-cleanup') {
+            steps {
+                sh 'docker system prune -af --volumes'
+            }
+        }
         stage('Checkout') {
             steps {
                 git url: 'https://github.com/InzynieriaOprogramowaniaAGH/MDO2026s_ITE.git',
@@ -35,6 +40,38 @@ pipeline {
         stage('Deploy') {
             steps {
                 dir('ITE/GCL3/KK419817/Sprawozdanie2/') {
+                    // Deploy testing app
+                    sh '''
+                docker build --no-cache -t container_deploy_image - <<EOF
+FROM express-build
+WORKDIR /app
+RUN echo 'const express = require("express"); \\
+const app = express(); \\
+app.get("/", (req, res) => res.send("This site works correctly")); \\
+app.listen(3000, () => console.log("App is listening on port 3000"));' > server.js
+EXPOSE 3000
+CMD ["node", "server.js"]
+EOF
+            '''
+                    sh 'docker run -d -p 3000:3000 --name container_deploy container_deploy_image'
+                    
+                    // Validate deployment
+                    echo 'Validating deployment...'
+
+                    sh '''
+OUTPUT=$(docker run --rm --network host alpine/curl sh -c '
+RESPONSE=$(curl -s http://localhost:3000)
+echo "Validation response: $RESPONSE"
+if echo "$RESPONSE" | grep -q "This site works correctly"; then
+    echo "Deploy validation SUCCESS"
+    exit 0
+else
+    echo "Deploy validation FAILED"
+    exit 1
+fi
+')
+echo "$OUTPUT"
+'''
                 }
             }
         }
@@ -42,12 +79,16 @@ pipeline {
         stage('Publish') {
             steps {
                 dir('ITE/GCL3/KK419817/Sprawozdanie2/') {
+                    echo 'Publishing...'
                 }
             }
         }
     }
 
     post {
+        always {
+            sh 'docker rm -f container_deploy || true'
+        }
         success {
             echo 'Pipeline success'
         }
