MB421332: Pętla oczekująca na plik JSON

diff --git a/ITE/GCL1/MB421332/Sprawozdanie2/Jenkinsfile b/ITE/GCL1/MB421332/Sprawozdanie2/Jenkinsfile
--- a/ITE/GCL1/MB421332/Sprawozdanie2/Jenkinsfile
+++ b/ITE/GCL1/MB421332/Sprawozdanie2/Jenkinsfile
@@ -59,7 +59,23 @@ pipeline {
                     sh 'docker logs app-production-container'
                     try {
                         echo "Verifying generated file output.json..."
-                        sh "docker exec app-production-container jq -e '.status == \"ok\"' output.json"
+                        sh '''
+                                ATTEMPTS=0
+                                MAX_ATTEMPTS=10
+                                
+                                until docker exec app-production-container test -f output.json; do
+                                    ATTEMPTS=$((ATTEMPTS+1))
+                                    if [ $ATTEMPTS -eq $MAX_ATTEMPTS ]; then
+                                        echo "ERROR: Timed out waiting for output.json to be created!"
+                                        exit 1
+                                    fi
+                                    echo "Waiting for the result file... (Próba $ATTEMPTS/$MAX_ATTEMPTS)"
+                                    sleep 1
+                                done
+                                
+                                echo "File output.json has been found! Running jq..."
+                                docker exec app-production-container jq -e '.status == "ok"' output.json
+                            '''
                         sh 'docker cp app-production-container:/app/output.json ./output.json'
                     } catch (Exception e) {
                         error("File output.json hasn't been created")
